[package]
name = "brainFuckInterpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.19", features = ["derive"]}
log = "0.4.22"
env_logger = "0.11.5"
ctrlc = "3.4.5"


[profile.release]
opt-level = 3
